services:
  tg-media-reposter:
    image: yaroslavgs/tg_media_reposter:latest
    restart: unless-stopped
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      OWNER_ID: "${OWNER_ID}"
      TARGET_CHANNEL_ID: "${TARGET_CHANNEL_ID}"
